apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simply-dns-webhook.fullname" . }}
  labels:
    app: {{ include "simply-dns-webhook.name" . }}
    chart: {{ include "simply-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "simply-dns-webhook.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: {{ include "simply-dns-webhook.name" . }}
    chart: {{ include "simply-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "simply-dns-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "simply-dns-webhook.fullname" . }}:auth-delegator
  labels:
    app: {{ include "simply-dns-webhook.name" . }}
    chart: {{ include "simply-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "simply-dns-webhook.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "simply-dns-webhook.fullname" . }}:domain-solver
  labels:
    app: {{ include "simply-dns-webhook.name" . }}
    chart: {{ include "simply-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "simply-dns-webhook.fullname" . }}:domain-solver
  labels:
    app: {{ include "simply-dns-webhook.name" . }}
    chart: {{ include "simply-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "simply-dns-webhook.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}
---
# Grant access to list flowcontrol
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "simply-dns-webhook.fullname" . }}:flow-control
  labels:
    app: {{ include "simply-dns-webhook.name" . }}
    chart: {{ include "simply-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - 'flowcontrol.apiserver.k8s.io'
    resources:
      - '*'
    verbs:
      - 'list'
      - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "simply-dns-webhook.fullname" . }}:flow-control
  labels:
    app: {{ include "simply-dns-webhook.name" . }}
    chart: {{ include "simply-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "simply-dns-webhook.fullname" . }}:flow-control
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "simply-dns-webhook.fullname" . }}
    namespace: {{ .Values.certManager.namespace }}
---
# Grant access to get secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "simply-dns-webhook.fullname" . }}:secret-access
  labels:
    app: {{ include "simply-dns-webhook.name" . }}
    chart: {{ include "simply-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - '*'
    resources:
      - 'secrets'
    verbs:
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "simply-dns-webhook.fullname" . }}:secret-access
  labels:
    app: {{ include "simply-dns-webhook.name" . }}
    chart: {{ include "simply-dns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "simply-dns-webhook.fullname" . }}:secret-access
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "simply-dns-webhook.fullname" . }}
    namespace: {{ .Values.certManager.namespace }}
---
# Grant access to manage challenge
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simply-dns-webhook:challenge-management
  labels:
    app: simply-dns-webhook
    chart: simply-dns-webhook
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - 'com.github.runnerm.cert-manager-simply-webhook'
    resources:
      - 'simply-dns-solver'
    verbs:
      - 'list'
      - 'watch'
      - 'create'
      - 'update'
      - 'patch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simply-dns-webhook:challenge-management
  labels:
    app: simply-dns-webhook
    chart: simply-dns-webhook
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: simply-dns-webhook:challenge-management
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ .Values.certManager.serviceAccountName }}
    namespace: {{ .Values.certManager.namespace }}